# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3
from tkinter import messagebox

from PyQt6 import QtCore, QtGui, QtWidgets

import qltaiKhoan
import quanlymonhoc
import Main
import TrangSV


class Ui_Login_Dialog(object):
    def setupUi(self, Login_Dialog):
        Login_Dialog.setObjectName("Login_Dialog")
        Login_Dialog.resize(381, 324)
        self.btnLogin = QtWidgets.QPushButton(parent=Login_Dialog)
        self.btnLogin.setGeometry(QtCore.QRect(140, 200, 91, 41))
        self.btnLogin.setObjectName("btnLogin")
        self.txtUser = QtWidgets.QLineEdit(parent=Login_Dialog)
        self.txtUser.setGeometry(QtCore.QRect(120, 90, 141, 31))
        self.txtUser.setObjectName("txtUser")
        self.txtPass = QtWidgets.QLineEdit(parent=Login_Dialog)
        self.txtPass.setGeometry(QtCore.QRect(120, 140, 141, 31))
        self.txtPass.setObjectName("txtPass")
        self.label = QtWidgets.QLabel(parent=Login_Dialog)
        self.label.setGeometry(QtCore.QRect(140, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Login_Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Login_Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 47, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Login_Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 260, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnTracuu = QtWidgets.QPushButton(parent=Login_Dialog)
        self.btnTracuu.setGeometry(QtCore.QRect(240, 250, 61, 31))
        self.btnTracuu.setObjectName("btnTracuu")

        self.retranslateUi(Login_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Login_Dialog)

        self.btnLogin.clicked.connect(self.login)
        self.btnTracuu.clicked.connect(self.tra_cuu)

    def retranslateUi(self, Login_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Login_Dialog.setWindowTitle(_translate("Login_Dialog", "Login_Dialog"))
        self.btnLogin.setText(_translate("Login_Dialog", "Đăng nhập"))
        self.label.setText(_translate("Login_Dialog", "Đăng nhập"))
        self.label_2.setText(_translate("Login_Dialog", "Tên đăng nhập"))
        self.label_3.setText(_translate("Login_Dialog", "Mật khẩu"))
        self.label_4.setText(_translate("Login_Dialog", "Tra cứu tài khoản sinh viên"))
        self.btnTracuu.setText(_translate("Login_Dialog", "Tra cứu"))

    def login(self):
        username = self.txtUser.text()
        password = self.txtPass.text()

        # Kết nối với cơ sở dữ liệu và lấy loại tài khoản
        conn = sqlite3.connect('../ui/ql_DiemHeDH.db')  # Thay 'your_database_name.db' bằng tên cơ sở dữ liệu thực tế của bạn
        cursor = conn.cursor()
        cursor.execute("SELECT LoaiTaiKhoan FROM ql_TaiKhoan WHERE User = ? AND Password = ?", (username, password))
        account_type = cursor.fetchone()

        if account_type is not None:
            if account_type[0] == 'Admin':
                self.window = QtWidgets.QMainWindow()
                self.ui = Main.Ui_Main()
                self.ui.setupUi(self.window)
                Login_Dialog.hide()
                self.window.show()
            elif account_type[0] == 'SinhVien':
                self.window = QtWidgets.QMainWindow()
                self.ui = TrangSV.Ui_TrangSinhVien()
                self.ui.setupUi(self.window)
                Login_Dialog.hide()
                self.window.show()
        else:
            messagebox.showinfo('Thông báo', 'Tên đăng nhập hoặc mật khẩu không chính xác')

    def tra_cuu(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = qltaiKhoan.Ui_QuanLyTaiKhoanSinhVien()
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Login_Dialog = QtWidgets.QDialog()
    ui = Ui_Login_Dialog()
    ui.setupUi(Login_Dialog)
    Login_Dialog.show()
    sys.exit(app.exec())
