# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QPushButton
import quanlymonhoc


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(831, 625)
        self.centralwidget = QtWidgets.QWidget(parent=Main)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_ql_diem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_ql_diem.setGeometry(QtCore.QRect(10, 90, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_ql_diem.setFont(font)
        self.btn_ql_diem.setObjectName("btn_ql_diem")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 10, 551, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_ql_monhoc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_ql_monhoc.setGeometry(QtCore.QRect(10, 160, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_ql_monhoc.setFont(font)
        self.btn_ql_monhoc.setObjectName("btn_ql_monhoc")
        self.btn_ql_Hssv = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_ql_Hssv.setGeometry(QtCore.QRect(10, 230, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_ql_Hssv.setFont(font)
        self.btn_ql_Hssv.setObjectName("btn_ql_Hssv")
        self.btn_ql_lop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_ql_lop.setGeometry(QtCore.QRect(10, 300, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_ql_lop.setFont(font)
        self.btn_ql_lop.setObjectName("btn_ql_lop")
        self.btn_ql_khoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_ql_khoa.setGeometry(QtCore.QRect(10, 370, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_ql_khoa.setFont(font)
        self.btn_ql_khoa.setObjectName("btn_ql_khoa")
        self.btn_ql_thongke = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_ql_thongke.setGeometry(QtCore.QRect(10, 440, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_ql_thongke.setFont(font)
        self.btn_ql_thongke.setObjectName("btn_ql_thongke")
        self.tblThanhVienNhom = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblThanhVienNhom.setGeometry(QtCore.QRect(160, 90, 581, 421))
        self.tblThanhVienNhom.setObjectName("tblThanhVienNhom")
        self.tblThanhVienNhom.setColumnCount(3)
        self.tblThanhVienNhom.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblThanhVienNhom.setItem(2, 2, item)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 21))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

        self.btn_ql_monhoc.clicked.connect(self.show_monhoc)
        self.btn_ql_khoa.clicked.connect(self.show_khoa)
        self.btn_ql_diem.clicked.connect(self.show_diem)
        self.btn_ql_lop.clicked.connect(self.show_lop)
        self.btn_ql_Hssv.clicked.connect(self.show_Hssv)
        self.btn_ql_thongke.clicked.connect(self.show_thongke)


    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Phần mềm quản lý điểm hệ đại học "))
        self.btn_ql_diem.setText(_translate("Main", "Quản lý điểm"))
        self.label.setText(_translate("Main", "Xây dựng phần mềm quản lý điểm hệ đại học "))
        self.btn_ql_monhoc.setText(_translate("Main", "Quản lý\n"
        "môn học"))
        self.btn_ql_Hssv.setText(_translate("Main", "Quản lý hồ sơ\n"
        "sinh viên  "))
        self.btn_ql_lop.setText(_translate("Main", "Quản lý\n"
        "lớp học"))
        self.btn_ql_khoa.setText(_translate("Main", "Quản lý khoa"))
        self.btn_ql_thongke.setText(_translate("Main", "Thống kê"))
        item = self.tblThanhVienNhom.verticalHeaderItem(0)
        item.setText(_translate("Main", "1"))
        item = self.tblThanhVienNhom.verticalHeaderItem(1)
        item.setText(_translate("Main", "2"))
        item = self.tblThanhVienNhom.verticalHeaderItem(2)
        item.setText(_translate("Main", "3"))
        item = self.tblThanhVienNhom.horizontalHeaderItem(0)
        item.setText(_translate("Main", "Mã Sinh Viên"))
        item = self.tblThanhVienNhom.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Tên Thành Viên"))
        item = self.tblThanhVienNhom.horizontalHeaderItem(2)
        item.setText(_translate("Main", "Lớp"))
        __sortingEnabled = self.tblThanhVienNhom.isSortingEnabled()
        self.tblThanhVienNhom.setSortingEnabled(False)
        item = self.tblThanhVienNhom.item(0, 1)
        item.setText(_translate("Main", "Nguyễn Đức Quý"))
        item = self.tblThanhVienNhom.item(0, 2)
        item.setText(_translate("Main", "DCCNTT12.10.5"))
        item = self.tblThanhVienNhom.item(1, 1)
        item.setText(_translate("Main", "Phạm Thị Phương Anh"))
        item = self.tblThanhVienNhom.item(1, 2)
        item.setText(_translate("Main", "DCCNTT12.10.5"))
        item = self.tblThanhVienNhom.item(2, 1)
        item.setText(_translate("Main", "Tạ Duy Khánh"))
        item = self.tblThanhVienNhom.item(2, 2)
        item.setText(_translate("Main", "DCCNTT12.10.5"))
        self.tblThanhVienNhom.setSortingEnabled(__sortingEnabled)



    def show_khoa(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = quanlymonhoc.Ui_Quanlymonhoc()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_thongke(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = quanlymonhoc.Ui_Quanlymonhoc()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_lop(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = quanlymonhoc.Ui_Quanlymonhoc()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_Hssv(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = quanlymonhoc.Ui_Quanlymonhoc()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_monhoc(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = quanlymonhoc.Ui_Quanlymonhoc()
        self.ui.setupUi(self.window)
        self.window.show()



    def show_diem(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = quanlymonhoc.Ui_Quanlymonhoc()
        self.ui.setupUi(self.window)
        self.window.show()






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec())
