# Form implementation generated from reading ui file 'QL_HS.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormQLHSSV(object):
    def setupUi(self, FormQLHSSV):
        FormQLHSSV.setObjectName("FormQLHSSV")
        FormQLHSSV.resize(1128, 780)
        self.label = QtWidgets.QLabel(parent=FormQLHSSV)
        self.label.setGeometry(QtCore.QRect(340, 20, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.xemHSSV = QtWidgets.QTableWidget(parent=FormQLHSSV)
        self.xemHSSV.setGeometry(QtCore.QRect(30, 90, 911, 401))
        self.xemHSSV.setObjectName("xemHSSV")
        self.xemHSSV.setColumnCount(8)
        self.xemHSSV.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.xemHSSV.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.xemHSSV.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.xemHSSV.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.xemHSSV.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.xemHSSV.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.xemHSSV.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.xemHSSV.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.xemHSSV.setHorizontalHeaderItem(7, item)
        self.pushButtonTK = QtWidgets.QPushButton(parent=FormQLHSSV)
        self.pushButtonTK.setGeometry(QtCore.QRect(960, 110, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonTK.setFont(font)
        self.pushButtonTK.setObjectName("pushButtonTK")
        self.pushButtonThemTTSV = QtWidgets.QPushButton(parent=FormQLHSSV)
        self.pushButtonThemTTSV.setGeometry(QtCore.QRect(960, 210, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonThemTTSV.setFont(font)
        self.pushButtonThemTTSV.setObjectName("pushButtonThemTTSV")
        self.pushButtonSuaTTSV = QtWidgets.QPushButton(parent=FormQLHSSV)
        self.pushButtonSuaTTSV.setGeometry(QtCore.QRect(960, 310, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSuaTTSV.setFont(font)
        self.pushButtonSuaTTSV.setObjectName("pushButtonSuaTTSV")
        self.label_2 = QtWidgets.QLabel(parent=FormQLHSSV)
        self.label_2.setGeometry(QtCore.QRect(20, 520, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=FormQLHSSV)
        self.lineEdit.setGeometry(QtCore.QRect(90, 520, 191, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=FormQLHSSV)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 590, 191, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=FormQLHSSV)
        self.label_3.setGeometry(QtCore.QRect(20, 590, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=FormQLHSSV)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 660, 191, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(parent=FormQLHSSV)
        self.label_4.setGeometry(QtCore.QRect(20, 660, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=FormQLHSSV)
        self.label_5.setGeometry(QtCore.QRect(350, 520, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=FormQLHSSV)
        self.lineEdit_4.setGeometry(QtCore.QRect(420, 590, 191, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(parent=FormQLHSSV)
        self.label_6.setGeometry(QtCore.QRect(350, 590, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=FormQLHSSV)
        self.lineEdit_5.setGeometry(QtCore.QRect(420, 660, 191, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(parent=FormQLHSSV)
        self.label_7.setGeometry(QtCore.QRect(350, 660, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=FormQLHSSV)
        self.lineEdit_6.setGeometry(QtCore.QRect(700, 520, 191, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(parent=FormQLHSSV)
        self.label_8.setGeometry(QtCore.QRect(650, 520, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(parent=FormQLHSSV)
        self.comboBox.setGeometry(QtCore.QRect(420, 520, 191, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButtonXoaTTSV = QtWidgets.QPushButton(parent=FormQLHSSV)
        self.pushButtonXoaTTSV.setGeometry(QtCore.QRect(960, 410, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonXoaTTSV.setFont(font)
        self.pushButtonXoaTTSV.setObjectName("pushButtonXoaTTSV")
        self.pushButtonLM = QtWidgets.QPushButton(parent=FormQLHSSV)
        self.pushButtonLM.setGeometry(QtCore.QRect(960, 510, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonLM.setFont(font)
        self.pushButtonLM.setObjectName("pushButtonLM")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=FormQLHSSV)
        self.lineEdit_7.setGeometry(QtCore.QRect(700, 590, 191, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(parent=FormQLHSSV)
        self.label_9.setGeometry(QtCore.QRect(640, 590, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(FormQLHSSV)
        QtCore.QMetaObject.connectSlotsByName(FormQLHSSV)
        self.load_data()
        self.xemHSSV.itemDoubleClicked.connect(self.Hien_thi)
        self.pushButtonLM.clicked.connect(self.Lam_moi)
        self.pushButtonTK.clicked.connect(self.tim_kiem)
        self.pushButtonThemTTSV.clicked.connect(self.them_SV)
        self.pushButtonSuaTTSV.clicked.connect(self.sua_SV)
        self.pushButtonXoaTTSV.clicked.connect(self.xoa_SV)

    def retranslateUi(self, FormQLHSSV):
        _translate = QtCore.QCoreApplication.translate
        FormQLHSSV.setWindowTitle(_translate("FormQLHSSV", "Form"))
        self.label.setText(_translate("FormQLHSSV", "Quản lý hồ sơ Sinh Viên"))
        item = self.xemHSSV.horizontalHeaderItem(0)
        item.setText(_translate("FormQLHSSV", "Mã SV"))
        item = self.xemHSSV.horizontalHeaderItem(1)
        item.setText(_translate("FormQLHSSV", "Tên SV"))
        item = self.xemHSSV.horizontalHeaderItem(2)
        item.setText(_translate("FormQLHSSV", "Tuổi"))
        item = self.xemHSSV.horizontalHeaderItem(3)
        item.setText(_translate("FormQLHSSV", "Giới tính"))
        item = self.xemHSSV.horizontalHeaderItem(4)
        item.setText(_translate("FormQLHSSV", "Địa chỉ"))
        item = self.xemHSSV.horizontalHeaderItem(5)
        item.setText(_translate("FormQLHSSV", "Email"))
        item = self.xemHSSV.horizontalHeaderItem(6)
        item.setText(_translate("FormQLHSSV", "SĐT"))
        item = self.xemHSSV.horizontalHeaderItem(7)
        item.setText(_translate("FormQLHSSV", "Mã lớp"))
        self.pushButtonTK.setText(_translate("FormQLHSSV", "Tìm Kiếm"))
        self.pushButtonThemTTSV.setText(_translate("FormQLHSSV", "Thêm T.T sinh viên"))
        self.pushButtonSuaTTSV.setText(_translate("FormQLHSSV", "Sửa T.T sinh viên"))
        self.label_2.setText(_translate("FormQLHSSV", "Mã SV"))
        self.label_3.setText(_translate("FormQLHSSV", "Tên SV"))
        self.label_4.setText(_translate("FormQLHSSV", "Tuổi"))
        self.label_5.setText(_translate("FormQLHSSV", "Giới tính"))
        self.label_6.setText(_translate("FormQLHSSV", "Địa chỉ"))
        self.label_7.setText(_translate("FormQLHSSV", "Email"))
        self.label_8.setText(_translate("FormQLHSSV", "SĐT"))
        self.comboBox.setItemText(0, _translate("FormQLHSSV", "Nam"))
        self.comboBox.setItemText(1, _translate("FormQLHSSV", "Nữ"))
        self.pushButtonXoaTTSV.setText(_translate("FormQLHSSV", "Xoá T.T sinh viên"))
        self.pushButtonLM.setText(_translate("FormQLHSSV", "Làm mới"))
        self.label_9.setText(_translate("FormQLHSSV", "Mã lớp"))

    def load_data(self):

        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()
        # Thực hiện truy vấn SQL để lấy tất cả các hàng từ bảng
        cursor.execute('''SELECT * FROM ql_HoSoSV''')
        hssv = cursor.fetchall()

        self.xemHSSV.setRowCount(len(hssv))
        # Duyệt qua từng hàng dữ liệu và từng cột dữ liệu trong kết quả truy vấn
        for row_index, row_data in enumerate(hssv):
            for col_index, col_data in enumerate(row_data):
                self.xemHSSV.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(col_data)))
        conn.close()

    def Hien_thi(self, item):

        # Lấy thông tin hàng được chọn trong tableWidget
        selected_row = item.row()
        MaSV = self.xemHSSV.item(selected_row, 0).text()
        TenSV = self.xemHSSV.item(selected_row, 1).text()
        Tuoi = self.xemHSSV.item(selected_row, 2).text()
        # GioiTinh = self.xemHSSV.item(selected_row, 3).text()
        DiaChi = self.xemHSSV.item(selected_row, 4).text()
        Email = self.xemHSSV.item(selected_row, 5).text()
        SDT = self.xemHSSV.item(selected_row, 6).text()
        MaLop = self.xemHSSV.item(selected_row, 7).text()

        # Hiển thị giá trị trong các lineEdit
        self.lineEdit.setText(MaSV)
        self.lineEdit_2.setText(TenSV)
        self.lineEdit_3.setText(Tuoi)
        self.lineEdit_4.setText(DiaChi)
        self.lineEdit_5.setText(Email)
        self.lineEdit_6.setText(SDT)
        # self.comboBox.setText(GioiTinh)
        self.lineEdit_7.setText(MaLop)

    def Lam_moi(self):
        # Xóa trắng các ô nhập liệu
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()
        self.load_data()

    def tim_kiem(self):
        # Lấy dữ liệu từ các ô nhập liệu
        MaSV = self.lineEdit.text()
        TenSV = self.lineEdit_2.text()
        Tuoi = self.lineEdit_3.text()
        GioiTinh = self.comboBox.currentText()
        DiaChi = self.lineEdit_4.text()
        Email = self.lineEdit_5.text()
        SDT = self.lineEdit_6.text()
        MaLop = self.lineEdit_7.text()

        # Xóa dữ liệu hiện có trong tableWidget
        self.xemHSSV.clearContents()

        # Kết nối đến cơ sở dữ liệu
        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()
        # Thực hiện lệnh SQL để tìm kiếm các lớp học
        cursor.execute(
            "SELECT * FROM ql_HoSoSV WHERE MaSV LIKE ? AND TenSV LIKE ? AND Tuoi LIKE ? AND GioiTinh LIKE ? AND DiaChi LIKE ? AND Email LIKE ? AND SDT LIKE ? AND MaLop LIKE ?",
            ('%' + MaSV + '%', '%' + TenSV + '%', '%' + Tuoi + '%',
             '%' + GioiTinh + '%', '%' + DiaChi + '%', '%' + Email + '%', '%' + SDT + '%', '%' + MaLop + '%'))
        hssv = cursor.fetchall()
        # Đặt số lượng hàng của tableWidget bằng số kết quả tìm được
        self.xemHSSV.setRowCount(len(hssv))
        # Hiển thị kết quả tìm kiếm trong tableWidget
        for row_index, row_data in enumerate(hssv):
            for col_index, col_data in enumerate(row_data):
                self.xemHSSV.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(col_data)))

        conn.close()

    def them_SV(self):

        # Lấy dữ liệu từ các ô nhập liệu
        MaSV = self.lineEdit.text()
        TenSV = self.lineEdit_2.text()
        Tuoi = self.lineEdit_3.text()
        GioiTinh = self.comboBox.currentText()
        DiaChi = self.lineEdit_4.text()
        Email = self.lineEdit_5.text()
        SDT = self.lineEdit_6.text()
        MaLop = self.lineEdit_7.text()
        # Kết nối đến cơ sở dữ liệu
        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()
        # Thực hiện lệnh SQL để chèn dữ liệu vào bảng
        cursor.execute(
            "INSERT INTO ql_HoSoSV (MaSV, TenSV, Tuoi,GioiTinh, DiaChi, Email, SDT, MaLop) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (MaSV, TenSV, Tuoi, GioiTinh, DiaChi, Email, SDT, MaLop))
        #  Lưu và đóng kết nối
        conn.commit()
        conn.close()

        self.load_data()

    def sua_SV(self):

        # Lấy dữ liệu từ các ô nhập liệu
        MaSV = self.lineEdit.text()
        TenSV = self.lineEdit_2.text()
        Tuoi = self.lineEdit_3.text()
        GioiTinh = self.comboBox.currentText()
        DiaChi = self.lineEdit_4.text()
        Email = self.lineEdit_5.text()
        SDT = self.lineEdit_6.text()
        MaLop = self.lineEdit_7.text()

        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()
        # Thực hiện lệnh SQL để cập nhật thông tin
        cursor.execute(
            "UPDATE ql_HoSoSV SET TenSV=?, Tuoi=?, GioiTinh=? , DiaChi=?, Email=?, SDT=?, MaLop=? WHERE MaSV=?",
            (TenSV, Tuoi, GioiTinh, DiaChi, Email, SDT, MaLop, MaSV))

        conn.commit()
        conn.close()

        self.load_data()

    def xoa_SV(self):

        # Lấy chỉ số của hàng đang được chọn trong bảng
        selected_row = self.xemHSSV.currentRow()
        # Kiểm tra nếu không có hàng nào được chọn thì hiển thị cảnh báo
        if selected_row == -1:
            QtWidgets.QMessageBox.warning(self, "Lỗi", "Vui lòng chọn một hàng để xóa.")
            return
        # Lấy mã lớp từ cột đầu tiên của hàng được chọn
        hssv = self.xemHSSV.item(selected_row, 0).text()

        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()
        # Thực hiện lệnh SQL để xóa lớp học theo mã SV
        cursor.execute("DELETE FROM ql_HoSoSV WHERE MaSV=?", (hssv,))

        conn.commit()
        conn.close()

        self.load_data()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    FormQLHSSV = QtWidgets.QWidget()
    ui = Ui_FormQLHSSV()
    ui.setupUi(FormQLHSSV)
    FormQLHSSV.show()
    sys.exit(app.exec())
