# Form implementation generated from reading ui file 'ql_lop.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QLlophoc(object):
    def setupUi(self, QLlophoc):
        QLlophoc.setObjectName("QLlophoc")
        QLlophoc.resize(980, 736)
        font = QtGui.QFont()
        font.setPointSize(10)
        QLlophoc.setFont(font)
        self.tableWidget = QtWidgets.QTableWidget(parent=QLlophoc)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 721, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.label = QtWidgets.QLabel(parent=QLlophoc)
        self.label.setGeometry(QtCore.QRect(350, 20, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditMakhoa = QtWidgets.QLineEdit(parent=QLlophoc)
        self.lineEditMakhoa.setGeometry(QtCore.QRect(110, 500, 261, 51))
        self.lineEditMakhoa.setObjectName("lineEditMakhoa")
        self.Timkiem = QtWidgets.QPushButton(parent=QLlophoc)
        self.Timkiem.setGeometry(QtCore.QRect(790, 90, 161, 61))
        self.Timkiem.setObjectName("Timkiem")
        self.TaoLopHoc = QtWidgets.QPushButton(parent=QLlophoc)
        self.TaoLopHoc.setGeometry(QtCore.QRect(790, 190, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TaoLopHoc.setFont(font)
        self.TaoLopHoc.setObjectName("TaoLopHoc")
        self.ChinhSualophoc = QtWidgets.QPushButton(parent=QLlophoc)
        self.ChinhSualophoc.setGeometry(QtCore.QRect(790, 290, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ChinhSualophoc.setFont(font)
        self.ChinhSualophoc.setObjectName("ChinhSualophoc")
        self.Xoalophoc = QtWidgets.QPushButton(parent=QLlophoc)
        self.Xoalophoc.setGeometry(QtCore.QRect(790, 390, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Xoalophoc.setFont(font)
        self.Xoalophoc.setObjectName("Xoalophoc")
        self.lineEditMaLop = QtWidgets.QLineEdit(parent=QLlophoc)
        self.lineEditMaLop.setGeometry(QtCore.QRect(110, 590, 261, 51))
        self.lineEditMaLop.setObjectName("lineEditMaLop")
        self.lineEditTenlop = QtWidgets.QLineEdit(parent=QLlophoc)
        self.lineEditTenlop.setGeometry(QtCore.QRect(480, 500, 261, 51))
        self.lineEditTenlop.setObjectName("lineEditTenlop")
        self.labelML = QtWidgets.QLabel(parent=QLlophoc)
        self.labelML.setGeometry(QtCore.QRect(20, 510, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelML.setFont(font)
        self.labelML.setObjectName("labelML")
        self.labelSP = QtWidgets.QLabel(parent=QLlophoc)
        self.labelSP.setGeometry(QtCore.QRect(20, 600, 111, 41))
        self.labelSP.setObjectName("labelSP")
        self.labelTenMH = QtWidgets.QLabel(parent=QLlophoc)
        self.labelTenMH.setGeometry(QtCore.QRect(400, 510, 71, 41))
        self.labelTenMH.setObjectName("labelTenMH")
        self.Lammoi = QtWidgets.QPushButton(parent=QLlophoc)
        self.Lammoi.setGeometry(QtCore.QRect(790, 490, 161, 61))
        self.Lammoi.setObjectName("Lammoi")

        self.retranslateUi(QLlophoc)
        QtCore.QMetaObject.connectSlotsByName(QLlophoc)
        self.load_data()
        self.TaoLopHoc.clicked.connect(self.them_lop_hoc)
        self.ChinhSualophoc.clicked.connect(self.sua_lop_hoc)
        self.Xoalophoc.clicked.connect(self.xoa_lop_hoc)
        self.Timkiem.clicked.connect(self.tim_kiem_lop_hoc)
        self.Lammoi.clicked.connect(self.Lam_moi)
        self.tableWidget.itemDoubleClicked.connect(self.Hien_thi)

    def retranslateUi(self, QLlophoc):
        _translate = QtCore.QCoreApplication.translate
        QLlophoc.setWindowTitle(_translate("QLlophoc", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("QLlophoc", "Mã khoa"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("QLlophoc", "Mã lớp "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("QLlophoc", "Tên lớp"))
        self.label.setText(_translate("QLlophoc", "Quản lý lớp học"))
        self.Timkiem.setText(_translate("QLlophoc", "Tìm Kiếm"))
        self.TaoLopHoc.setText(_translate("QLlophoc", "Tạo lớp học mới"))
        self.ChinhSualophoc.setText(_translate("QLlophoc", "Chỉnh sửa T.T lớp học"))
        self.Xoalophoc.setText(_translate("QLlophoc", "Xóa lớp học"))
        self.labelML.setText(_translate("QLlophoc", "Mã Khoa"))
        self.labelSP.setText(_translate("QLlophoc", "Mã Lớp"))
        self.labelTenMH.setText(_translate("QLlophoc", "Tên Lớp"))
        self.Lammoi.setText(_translate("QLlophoc", "Làm mới"))

    def load_data(self):

        # Kết nối đến cơ sở dữ liệu
        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()

        # Thực hiện truy vấn SQL để lấy tất cả các hàng từ bảng ql_Lop
        cursor.execute('''SELECT * FROM ql_Lop''')
        classes = cursor.fetchall()

        self.tableWidget.setRowCount(len(classes))
        # Duyệt qua từng hàng dữ liệu và từng cột dữ liệu trong kết quả truy vấn
        for row_index, row_data in enumerate(classes):
            for col_index, col_data in enumerate(row_data):
                self.tableWidget.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(col_data)))

        # Đóng kết nối cơ sở dữ liệu
        conn.close()

    def Lam_moi(self):
        # Xóa trắng các ô nhập liệu
        self.lineEditMakhoa.clear()
        self.lineEditMaLop.clear()
        self.lineEditTenlop.clear()

    def Hien_thi(self, item):
        # Lấy thông tin hàng được chọn trong tableWidget
        selected_row = item.row()
        MaKhoa = self.tableWidget.item(selected_row, 0).text()
        MaLop = self.tableWidget.item(selected_row, 1).text()
        TenLop = self.tableWidget.item(selected_row, 2).text()

        # Hiển thị giá trị trong các lineEdit
        self.lineEditMakhoa.setText(MaKhoa)
        self.lineEditMaLop.setText(MaLop)
        self.lineEditTenlop.setText(TenLop)

    def tim_kiem_lop_hoc(self):
        # Lấy dữ liệu từ các ô nhập liệu
        MaKhoa = self.lineEditMakhoa.text()
        MaLop = self.lineEditMaLop.text()
        TenLop = self.lineEditTenlop.text()

        # Xóa dữ liệu hiện có trong tableWidget
        self.tableWidget.clearContents()

        # Kết nối đến cơ sở dữ liệu
        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()
        # Thực hiện lệnh SQL để tìm kiếm các lớp học
        cursor.execute(
            "SELECT * FROM ql_Lop WHERE MaKhoa LIKE ? AND MaLop LIKE ? AND TenLop LIKE ? ",
            ('%' + MaKhoa + '%', '%' + MaLop + '%', '%' + TenLop + '%'))
        classes = cursor.fetchall()
        # Đặt số lượng hàng của tableWidget bằng số kết quả tìm được
        self.tableWidget.setRowCount(len(classes))
        # Hiển thị kết quả tìm kiếm trong tableWidget
        for row_index, row_data in enumerate(classes):
            for col_index, col_data in enumerate(row_data):
                self.tableWidget.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(col_data)))

        conn.close()

    def them_lop_hoc(self):
        # Lấy dữ liệu từ các ô nhập liệu
        MaKhoa = self.lineEditMakhoa.text()
        MaLop = self.lineEditMaLop.text()
        TenLop = self.lineEditTenlop.text()

        # Kết nối đến cơ sở dữ liệu
        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()
        # Thực hiện lệnh SQL để chèn dữ liệu vào bảng ql_Lop
        cursor.execute("INSERT INTO ql_Lop (MaKhoa, MaLop, TenLop) VALUES (?, ?, ?)",
                       (MaKhoa, MaLop, TenLop))
        #  Lưu và đóng kết nối
        conn.commit()
        conn.close()
        # Tải lại dữ liệu
        self.load_data()

    def sua_lop_hoc(self):
        # Lấy dữ liệu từ các ô nhập liệu
        MaKhoa = self.lineEditMakhoa.text()
        MaLop = self.lineEditMaLop.text()
        TenLop = self.lineEditTenlop.text()
        # Kết nối đến cơ sở dữ liệu
        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()
        # Thực hiện lệnh SQL để cập nhật thông tin lớp học
        cursor.execute("UPDATE ql_Lop SET MaLop=?, TenLop=? WHERE MaKhoa=?",
                       (MaLop, TenLop, MaKhoa))
        #  Lưu và đóng kết nối
        conn.commit()
        conn.close()
        self.load_data()

    def xoa_lop_hoc(self):
        # Lấy chỉ số của hàng đang được chọn trong tableWidget
        selected_row = self.tableWidget.currentRow()
        # Kiểm tra nếu không có hàng nào được chọn thì hiển thị cảnh báo
        if selected_row == -1:
            QtWidgets.QMessageBox.warning(self, "Lỗi", "Vui lòng chọn một hàng để xóa.")
            return
        # Lấy mã lớp từ cột đầu tiên của hàng được chọn
        MaKhoa = self.tableWidget.item(selected_row, 0).text()

        conn = sqlite3.connect('ql_DiemHeDH.db')
        cursor = conn.cursor()
        # Thực hiện lệnh SQL để xóa lớp học theo mã lớp
        cursor.execute("DELETE FROM ql_Lop WHERE MaKhoa=?", (MaKhoa,))

        conn.commit()
        conn.close()

        self.load_data()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    QLlophoc = QtWidgets.QWidget()
    ui = Ui_QLlophoc()
    ui.setupUi(QLlophoc)
    QLlophoc.show()
    sys.exit(app.exec())
