# Form implementation generated from reading ui file 'qlAccount.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QuanLyTaiKhoan(object):
    def setupUi(self, QuanLyTaiKhoan):
        QuanLyTaiKhoan.setObjectName("QuanLyTaiKhoan")
        QuanLyTaiKhoan.resize(790, 545)
        self.centralwidget = QtWidgets.QWidget(parent=QuanLyTaiKhoan)
        self.centralwidget.setObjectName("centralwidget")
        self.tblTaiKhoan = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblTaiKhoan.setGeometry(QtCore.QRect(40, 40, 561, 311))
        self.tblTaiKhoan.setObjectName("tblTaiKhoan")
        self.tblTaiKhoan.setColumnCount(3)
        self.tblTaiKhoan.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaiKhoan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaiKhoan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaiKhoan.setHorizontalHeaderItem(2, item)
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(640, 40, 111, 51))
        self.btnAdd.setObjectName("btnAdd")
        self.btnSua = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSua.setGeometry(QtCore.QRect(640, 110, 111, 51))
        self.btnSua.setObjectName("btnSua")
        self.btnXoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXoa.setGeometry(QtCore.QRect(640, 180, 111, 51))
        self.btnXoa.setObjectName("btnXoa")
        self.btnSeach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSeach.setGeometry(QtCore.QRect(640, 250, 111, 51))
        self.btnSeach.setObjectName("btnSeach")
        self.btnRefesh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRefesh.setGeometry(QtCore.QRect(640, 320, 111, 51))
        self.btnRefesh.setObjectName("btnRefesh")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 440, 47, 13))
        self.label_3.setObjectName("label_3")
        self.txtUser = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtUser.setGeometry(QtCore.QRect(120, 370, 141, 31))
        self.txtUser.setObjectName("txtUser")
        self.txtPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPass.setGeometry(QtCore.QRect(120, 430, 141, 31))
        self.txtPass.setObjectName("txtPass")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 380, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 380, 81, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(410, 370, 141, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        QuanLyTaiKhoan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=QuanLyTaiKhoan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 26))
        self.menubar.setObjectName("menubar")
        QuanLyTaiKhoan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=QuanLyTaiKhoan)
        self.statusbar.setObjectName("statusbar")
        QuanLyTaiKhoan.setStatusBar(self.statusbar)

        self.retranslateUi(QuanLyTaiKhoan)
        QtCore.QMetaObject.connectSlotsByName(QuanLyTaiKhoan)

    def retranslateUi(self, QuanLyTaiKhoan):
        _translate = QtCore.QCoreApplication.translate
        QuanLyTaiKhoan.setWindowTitle(_translate("QuanLyTaiKhoan", "QuanLyTaiKhoan"))
        item = self.tblTaiKhoan.horizontalHeaderItem(0)
        item.setText(_translate("QuanLyTaiKhoan", "User"))
        item = self.tblTaiKhoan.horizontalHeaderItem(1)
        item.setText(_translate("QuanLyTaiKhoan", "Password"))
        item = self.tblTaiKhoan.horizontalHeaderItem(2)
        item.setText(_translate("QuanLyTaiKhoan", "Loại tài khoản"))
        self.btnAdd.setText(_translate("QuanLyTaiKhoan", "Thêm"))
        self.btnSua.setText(_translate("QuanLyTaiKhoan", "Sửa"))
        self.btnXoa.setText(_translate("QuanLyTaiKhoan", "Xóa"))
        self.btnSeach.setText(_translate("QuanLyTaiKhoan", "Tìm kiếm"))
        self.btnRefesh.setText(_translate("QuanLyTaiKhoan", "Làm mới"))
        self.label_3.setText(_translate("QuanLyTaiKhoan", "Pass"))
        self.label.setText(_translate("QuanLyTaiKhoan", "User"))
        self.label_2.setText(_translate("QuanLyTaiKhoan", "Loại tài khoản"))
        self.comboBox.setItemText(0, _translate("QuanLyTaiKhoan", "Admin"))
        self.comboBox.setItemText(1, _translate("QuanLyTaiKhoan", "Sinh Vien"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QuanLyTaiKhoan = QtWidgets.QMainWindow()
    ui = Ui_QuanLyTaiKhoan()
    ui.setupUi(QuanLyTaiKhoan)
    QuanLyTaiKhoan.show()
    sys.exit(app.exec())
