# Form implementation generated from reading ui file 'quanlykhoa.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QuanLyKhoa(object):
    def setupUi(self, QuanLyKhoa):
        QuanLyKhoa.setObjectName("QuanLyKhoa")
        QuanLyKhoa.resize(665, 504)
        self.centralwidget = QtWidgets.QWidget(parent=QuanLyKhoa)
        self.centralwidget.setObjectName("centralwidget")
        self.btnTimkiem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTimkiem.setGeometry(QtCore.QRect(380, 290, 75, 23))
        self.btnTimkiem.setObjectName("btnTimkiem")
        self.btnThem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnThem.setGeometry(QtCore.QRect(20, 290, 75, 23))
        self.btnThem.setObjectName("btnThem")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 170, 81, 21))
        self.label_3.setObjectName("label_3")
        self.lineEditMakhoa = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditMakhoa.setGeometry(QtCore.QRect(410, 80, 171, 31))
        self.lineEditMakhoa.setObjectName("lineEditMakhoa")
        self.btnXoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXoa.setGeometry(QtCore.QRect(260, 290, 75, 23))
        self.btnXoa.setObjectName("btnXoa")
        self.tableKhoa = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableKhoa.setGeometry(QtCore.QRect(50, 30, 261, 231))
        self.tableKhoa.setObjectName("tableKhoa")
        self.tableKhoa.setColumnCount(2)
        self.tableKhoa.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableKhoa.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableKhoa.setHorizontalHeaderItem(1, item)
        self.btnSua = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSua.setGeometry(QtCore.QRect(140, 290, 75, 23))
        self.btnSua.setObjectName("btnSua")
        self.btnLammoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLammoi.setGeometry(QtCore.QRect(500, 290, 75, 23))
        self.btnLammoi.setObjectName("btnLammoi")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 90, 81, 21))
        self.label.setObjectName("label")
        self.lineEditTenkhoa = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditTenkhoa.setGeometry(QtCore.QRect(410, 160, 171, 31))
        self.lineEditTenkhoa.setObjectName("lineEditTenkhoa")
        QuanLyKhoa.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=QuanLyKhoa)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 21))
        self.menubar.setObjectName("menubar")
        QuanLyKhoa.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=QuanLyKhoa)
        self.statusbar.setObjectName("statusbar")
        QuanLyKhoa.setStatusBar(self.statusbar)

        self.retranslateUi(QuanLyKhoa)
        QtCore.QMetaObject.connectSlotsByName(QuanLyKhoa)
        self.load_data()
        self.btnThem.clicked.connect(self.them_khoa)
        self.btnSua.clicked.connect(self.sua_khoa)
        self.tableKhoa.itemDoubleClicked.connect(self.hien_thi)
        self.btnXoa.clicked.connect(self.xoa_khoa)
        self.btnLammoi.clicked.connect(self.lam_moi)
        self.btnTimkiem.clicked.connect(self.tim_kiem)

    def retranslateUi(self, QuanLyKhoa):
        _translate = QtCore.QCoreApplication.translate
        QuanLyKhoa.setWindowTitle(_translate("QuanLyKhoa", "QuanLyKhoa"))
        self.btnTimkiem.setText(_translate("QuanLyKhoa", "Tìm kiếm"))
        self.btnThem.setText(_translate("QuanLyKhoa", "Thêm"))
        self.label_3.setText(_translate("QuanLyKhoa", "Tên Khoa"))
        self.btnXoa.setText(_translate("QuanLyKhoa", "Xóa"))
        item = self.tableKhoa.horizontalHeaderItem(0)
        item.setText(_translate("QuanLyKhoa", "Mã Khoa"))
        item = self.tableKhoa.horizontalHeaderItem(1)
        item.setText(_translate("QuanLyKhoa", "Tên Khoa"))
        self.btnSua.setText(_translate("QuanLyKhoa", "Sửa"))
        self.btnLammoi.setText(_translate("QuanLyKhoa", "Làm mới"))
        self.label.setText(_translate("QuanLyKhoa", "Mã Khoa"))

    def load_data(self):
        conn = sqlite3.connect('ql_diemHeDH.db')
        curses = conn.cursor()

        curses.execute('''SELECT * FROM ql_Khoa''')
        khoa = curses.fetchall()

        self.tableKhoa.setRowCount(len(khoa))
        for row_index, row_data in enumerate(khoa):
            for col_index, col_data in enumerate(row_data):
                self.tableKhoa.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(col_data)))
        conn.close()

    def them_khoa(self):
        # Xử lý sự kiện khi nhấn nút "Thêm"
        makhoa = self.lineEditMakhoa.text()
        tenkhoa = self.lineEditTenkhoa.text()

        # Thực hiện thêm dữ liệu vào bảng diem
        conn = sqlite3.connect("ql_diemHeDH.db")
        cursor = conn.cursor()
        cursor.execute("INSERT INTO ql_Khoa (MaKhoa, TenKhoa) VALUES (?, ?)",
                       (makhoa, tenkhoa))
        conn.commit()
        conn.close()
        self.load_data()

    def sua_khoa(self):
        # Xử lý sự kiện khi nhấn nút "sửa"
        makhoa = self.lineEditMakhoa.text()
        tenkhoa = self.lineEditTenkhoa.text()

        # Thực hiện sửa dữ liệu vào bảng diem
        conn = sqlite3.connect("ql_diemHeDH.db")
        cursor = conn.cursor()
        cursor.execute("UPDATE ql_Khoa SET TenKhoa = ? WHERE MaKhoa = ?",
                       (tenkhoa, makhoa))
        conn.commit()
        conn.close()
        self.load_data()

    def hien_thi(self, item):
        # lấy dữ liệu từ tablewidge
        selected_row = item.row()
        makhoa = self.tableKhoa.item(selected_row, 0).text()
        tenkhoa = self.tableKhoa.item(selected_row, 1).text()

        # Hiển thị giá trị trong các lineEdit
        self.lineEditMakhoa.setText(makhoa)
        self.lineEditTenkhoa.setText(tenkhoa)

    def xoa_khoa(self):
        # Xử lý sự kiện khi nhấn nút "Xóa"
        selected_row = self.tableKhoa.currentRow()

        if selected_row == -1:  # Kiểm tra xem có hàng nào được chọn không
            QtWidgets.QMessageBox.warning(self, "lỗi", "Vui lòng chọn một hàng để xóa")
            return

        makhoa = self.tableKhoa.item(selected_row, 0).text()  # Lấy mã sinh viên từ hàng được chọn

        conn = sqlite3.connect("ql_diemHeDH.db")
        cursor = conn.cursor()
        # Thực hiện xóa dữ liệu từ bảng diem
        cursor.execute("DELETE FROM ql_Khoa WHERE MaKhoa = ?", (makhoa,))
        conn.commit()
        conn.close()
        self.load_data()

    def tim_kiem(self):
        makhoa = self.lineEditMakhoa.text()
        tenkhoa = self.lineEditTenkhoa.text()

        # Xóa dữ liệu hiện có trong tableWidget
        self.tableKhoa.clearContents()

        # Kết nối đến cơ sở dữ liệu
        conn = sqlite3.connect('ql_diemHeDH.db')
        cursor = conn.cursor()

        cursor.execute(
            "SELECT * FROM ql_Khoa WHERE MaKhoa LIKE ? AND TenKhoa LIKE ?",
            ('%' + makhoa + '%', '%' + tenkhoa + '%'))
        khoa = cursor.fetchall()

        self.tableKhoa.setRowCount(len(khoa))
        for row_index, row_data in enumerate(khoa):
            for col_index, col_data in enumerate(row_data):
                self.tableKhoa.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(col_data)))

        conn.close()

    def lam_moi(self):
        # Xóa nội dung trong các lineEdit
        self.lineEditMakhoa.clear()
        self.lineEditTenkhoa.clear()
        self.load_data()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    QuanLyKhoa = QtWidgets.QMainWindow()
    ui = Ui_QuanLyKhoa()
    ui.setupUi(QuanLyKhoa)
    QuanLyKhoa.show()
    sys.exit(app.exec())
