# Form implementation generated from reading ui file 'quanlydiem.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QuanLyDiem(object):
    def setupUi(self, QuanLyDiem):
        QuanLyDiem.setObjectName("QuanLyDiem")
        QuanLyDiem.resize(928, 662)
        self.centralwidget = QtWidgets.QWidget(parent=QuanLyDiem)
        self.centralwidget.setObjectName("centralwidget")
        self.btnTimkiem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTimkiem.setGeometry(QtCore.QRect(840, 220, 75, 23))
        self.btnTimkiem.setObjectName("btnTimkiem")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 440, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 380, 81, 21))
        self.label_3.setObjectName("label_3")
        self.btnLammoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLammoi.setGeometry(QtCore.QRect(840, 280, 75, 23))
        self.btnLammoi.setObjectName("btnLammoi")
        self.lineEditDiem1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditDiem1.setGeometry(QtCore.QRect(610, 370, 171, 31))
        self.lineEditDiem1.setObjectName("lineEditDiem1")
        self.btnXoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXoa.setGeometry(QtCore.QRect(840, 170, 75, 23))
        self.btnXoa.setObjectName("btnXoa")
        self.btnSua = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSua.setGeometry(QtCore.QRect(840, 110, 75, 23))
        self.btnSua.setObjectName("btnSua")
        self.tableDiem = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableDiem.setGeometry(QtCore.QRect(10, 40, 801, 321))
        self.tableDiem.setObjectName("tableDiem")
        self.tableDiem.setColumnCount(8)
        self.tableDiem.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableDiem.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiem.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableDiem.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiem.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableDiem.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableDiem.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiem.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiem.setHorizontalHeaderItem(7, item)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 450, 81, 21))
        self.label_2.setObjectName("label_2")
        self.btnThem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnThem.setGeometry(QtCore.QRect(840, 50, 75, 23))
        self.btnThem.setObjectName("btnThem")
        self.btnDiemtb = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDiemtb.setGeometry(QtCore.QRect(840, 330, 71, 28))
        self.btnDiemtb.setObjectName("btnDiemtb")
        self.lineEditMaSV = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditMaSV.setGeometry(QtCore.QRect(140, 380, 171, 31))
        self.lineEditMaSV.setObjectName("lineEditMaSV")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 380, 81, 21))
        self.label.setObjectName("label")
        self.lineEditDiem2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditDiem2.setGeometry(QtCore.QRect(610, 440, 171, 31))
        self.lineEditDiem2.setObjectName("lineEditDiem2")
        self.lineEditTenSV = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditTenSV.setGeometry(QtCore.QRect(140, 450, 171, 31))
        self.lineEditTenSV.setObjectName("lineEditTenSV")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 520, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 580, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 510, 81, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(510, 570, 81, 21))
        self.label_8.setObjectName("label_8")
        self.lineEditMaMonhoc = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditMaMonhoc.setGeometry(QtCore.QRect(140, 520, 171, 31))
        self.lineEditMaMonhoc.setObjectName("lineEditMaMonhoc")
        self.lineEditMalop = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditMalop.setGeometry(QtCore.QRect(140, 580, 171, 31))
        self.lineEditMalop.setObjectName("lineEditMalop")
        self.lineEditDiemTB = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditDiemTB.setGeometry(QtCore.QRect(610, 510, 171, 31))
        self.lineEditDiemTB.setObjectName("lineEditDiemTB")
        self.lineEditXeploai = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditXeploai.setGeometry(QtCore.QRect(610, 570, 171, 31))
        self.lineEditXeploai.setObjectName("lineEditXeploai")
        QuanLyDiem.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=QuanLyDiem)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 26))
        self.menubar.setObjectName("menubar")
        QuanLyDiem.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=QuanLyDiem)
        self.statusbar.setObjectName("statusbar")
        QuanLyDiem.setStatusBar(self.statusbar)

        self.retranslateUi(QuanLyDiem)
        QtCore.QMetaObject.connectSlotsByName(QuanLyDiem)
        self.load_data()
        self.btnTimkiem.clicked.connect(self.tim_kiem)
        self.btnSua.clicked.connect(self.sua_diem)
        self.btnLammoi.clicked.connect(self.lam_moi)
        self.btnThem.clicked.connect(self.them_diem)
        self.btnXoa.clicked.connect(self.xoa_diem)
        self.tableDiem.itemDoubleClicked.connect(self.hien_thi)
        self.btnDiemtb.clicked.connect(self.Diem_tb)

    def retranslateUi(self, QuanLyDiem):
        _translate = QtCore.QCoreApplication.translate
        QuanLyDiem.setWindowTitle(_translate("QuanLyDiem", "QuanLyDiem"))
        self.btnTimkiem.setText(_translate("QuanLyDiem", "Tìm kiếm"))
        self.label_4.setText(_translate("QuanLyDiem", "Điểm lần 2"))
        self.label_3.setText(_translate("QuanLyDiem", "Điểm lần 1"))
        self.btnLammoi.setText(_translate("QuanLyDiem", "Làm mới"))
        self.btnXoa.setText(_translate("QuanLyDiem", "Xóa"))
        self.btnSua.setText(_translate("QuanLyDiem", "Sửa"))
        item = self.tableDiem.horizontalHeaderItem(0)
        item.setText(_translate("QuanLyDiem", "Mã  Sinh Viên"))
        item = self.tableDiem.horizontalHeaderItem(1)
        item.setText(_translate("QuanLyDiem", "Tên Sinh Viên"))
        item = self.tableDiem.horizontalHeaderItem(2)
        item.setText(_translate("QuanLyDiem", "Mã Môn Học"))
        item = self.tableDiem.horizontalHeaderItem(3)
        item.setText(_translate("QuanLyDiem", "Mã Lớp"))
        item = self.tableDiem.horizontalHeaderItem(4)
        item.setText(_translate("QuanLyDiem", "Điểm lần 1"))
        item = self.tableDiem.horizontalHeaderItem(5)
        item.setText(_translate("QuanLyDiem", "Điểm lần 2"))
        item = self.tableDiem.horizontalHeaderItem(6)
        item.setText(_translate("QuanLyDiem", "Điểm TB"))
        item = self.tableDiem.horizontalHeaderItem(7)
        item.setText(_translate("QuanLyDiem", "Xếp Loại"))
        self.label_2.setText(_translate("QuanLyDiem", "Tên sinh viên"))
        self.btnThem.setText(_translate("QuanLyDiem", "Thêm"))
        self.btnDiemtb.setText(_translate("QuanLyDiem", "Điểm TB"))
        self.label.setText(_translate("QuanLyDiem", "Mã sinh viên"))
        self.label_5.setText(_translate("QuanLyDiem", "Mã môn học"))
        self.label_6.setText(_translate("QuanLyDiem", "Mã lớp"))
        self.label_7.setText(_translate("QuanLyDiem", "Điểm TB"))
        self.label_8.setText(_translate("QuanLyDiem", "Xếp loại"))

    def load_data(self):
        conn = sqlite3.connect('ql_diemHeDH.db')
        curses = conn.cursor()

        curses.execute('''SELECT * FROM ql_Diem''')
        diem = curses.fetchall()

        self.tableDiem.setRowCount(len(diem))
        for row_index, row_data in enumerate(diem):
            for col_index, col_data in enumerate(row_data):
                self.tableDiem.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(col_data)))
        conn.close()

    def Diem_tb(self):
        try:
            diem1 = float(self.lineEditDiem1.text())
            diem2 = float(self.lineEditDiem2.text())
            Diemtb = (diem1 + diem2) / 2
            self.lineEditDiemTB.setText(str(Diemtb))

            if Diemtb >= 9:
                xeploai = 'A'
            elif 8 <= Diemtb < 9:
                xeploai = 'B'
            elif 6 <= Diemtb < 8:
                xeploai = 'C'
            elif 4.5 <= Diemtb < 6:
                xeploai = 'D'
            else:
                xeploai = 'F'

            self.lineEditXeploai.setText(xeploai)

        except ValueError:
            self.lineEditDiemTB.setText('')
            self.lineEditXeploai.setText('')

    def them_diem(self):
        # Xử lý sự kiện khi nhấn nút "Thêm"
        masv = self.lineEditMaSV.text()
        tensv = self.lineEditTenSV.text()
        mamonhoc = self.lineEditMaMonhoc.text()
        malop = self.lineEditMalop.text()
        diem1 = self.lineEditDiem1.text()
        diem2 = self.lineEditDiem2.text()
        diemtb = self.lineEditDiemTB.text()
        xeploai = self.lineEditXeploai.text()

        # Thực hiện thêm dữ liệu vào bảng diem
        conn = sqlite3.connect("ql_diemHeDH.db")
        cursor = conn.cursor()
        cursor.execute('''
                    INSERT INTO ql_Diem (MaSV, TenSV, MaMH, MaLop, DiemLan1, DiemLan2, DiemTrungBinh, XepLoai)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ''', (masv, tensv, mamonhoc, malop, diem1, diem2, diemtb, xeploai))
        conn.commit()
        conn.close()
        self.load_data()

    def xoa_diem(self):
        # Xử lý sự kiện khi nhấn nút "Xóa"
        selected_row = self.tableDiem.currentRow()

        if selected_row == -1:  # Kiểm tra xem có hàng nào được chọn không
            QtWidgets.QMessageBox.warning(self, "lỗi", "Vui lòng chọn một hàng để xóa")
            return

        masv = self.tableDiem.item(selected_row, 0).text()  # Lấy mã sinh viên từ hàng được chọn

        conn = sqlite3.connect("ql_diemHeDH.db")
        cursor = conn.cursor()
        # Thực hiện xóa dữ liệu từ bảng diem
        cursor.execute("DELETE FROM ql_Diem WHERE MaSV = ?", (masv,))
        conn.commit()
        conn.close()
        self.load_data()

    def sua_diem(self):
        masv = self.lineEditMaSV.text()
        tensv = self.lineEditTenSV.text()
        mamh = self.lineEditMaMonhoc.text()
        malop = self.lineEditMalop.text()
        diem1 = self.lineEditDiem1.text()
        diem2 = self.lineEditDiem2.text()
        diemtb = self.lineEditDiemTB.text()
        xeploai = self.lineEditXeploai.text()

        # Thực hiện thêm dữ liệu vào bảng diem
        conn = sqlite3.connect("ql_diemHeDH.db")
        cursor = conn.cursor()
        cursor.execute("""
                    UPDATE ql_Diem
                    SET TenSV = ?, MaMH = ?, MaLop= ?, DiemLan1 = ?, DiemLan2 = ?, DiemTrungBinh = ?, XepLoai = ?
                    WHERE MaSV = ?
                """, (tensv, mamh, malop, diem1, diem2, diemtb, xeploai, masv))

        conn.commit()
        conn.close()
        self.load_data()

    def hien_thi(self, item):
        selected_row = item.row()
        masv = self.tableDiem.item(selected_row, 0).text()
        tensv = self.tableDiem.item(selected_row, 1).text()
        mamonhoc = self.tableDiem.item(selected_row, 2).text()
        malop = self.tableDiem.item(selected_row, 3).text()
        diem1 = self.tableDiem.item(selected_row, 4).text()
        diem2 = self.tableDiem.item(selected_row, 5).text()
        diemtb = self.tableDiem.item(selected_row, 6).text()
        xeploai = self.tableDiem.item(selected_row, 7).text()

        # Hiển thị giá trị trong các lineEdit
        self.lineEditMaMonhoc.setText(mamonhoc)
        self.lineEditMaSV.setText(masv)
        self.lineEditDiem1.setText(diem1)
        self.lineEditDiem2.setText(diem2)
        self.lineEditDiemTB.setText(diemtb)
        self.lineEditMalop.setText(malop)
        self.lineEditXeploai.setText(xeploai)
        self.lineEditTenSV.setText(tensv)

        self.load_data()

    def tim_kiem(self):
        masv = self.lineEditMaSV.text()
        tensv = self.lineEditTenSV.text()
        mamonhoc = self.lineEditMaMonhoc.text()
        malop = self.lineEditMalop.text()
        diem1 = self.lineEditDiem1.text()
        diem2 = self.lineEditDiem2.text()
        diemtb = self.lineEditDiemTB.text()
        xeploai = self.lineEditXeploai.text()

        # Xóa dữ liệu hiện có trong tableWidget
        self.tableDiem.clearContents()

        # Kết nối đến cơ sở dữ liệu
        conn = sqlite3.connect('ql_diemHeDH.db')
        cursor = conn.cursor()

        cursor.execute(
            "SELECT * FROM ql_Diem WHERE MaSV LIKE ? AND TenSV LIKE ? AND MaMH LIKE ? AND MaLop LIKE ? AND DiemLan1 LIKE ?"
            " AND DiemLan2 LIKE ? AND DiemTrungBinh LIKE ? AND XepLoai LIKE ?",
            ('%' + masv + '%', '%' + tensv + '%', '%' + mamonhoc + '%', '%' + malop + '%', '%' + diem1 + '%',
             '%' + diem2 + '%', '%' + diemtb + '%', '%' + xeploai + '%'))
        diem = cursor.fetchall()

        self.tableDiem.setRowCount(len(diem))
        for row_index, row_data in enumerate(diem):
            for col_index, col_data in enumerate(row_data):
                self.tableDiem.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(col_data)))

        conn.close()

    def lam_moi(self):
        # Xóa nội dung trong các lineEdit
        self.lineEditMaSV.clear()
        self.lineEditTenSV.clear()
        self.lineEditMaMonhoc.clear()
        self.lineEditMalop.clear()
        self.lineEditDiem1.clear()
        self.lineEditDiem2.clear()
        self.lineEditDiemTB.clear()
        self.lineEditXeploai.clear()
        self.load_data()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    QuanLyDiem = QtWidgets.QMainWindow()
    ui = Ui_QuanLyDiem()
    ui.setupUi(QuanLyDiem)
    QuanLyDiem.show()
    sys.exit(app.exec())
