# Form implementation generated from reading ui file 'TrangSV.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem


class Ui_TrangSinhVien(object):
    def setupUi(self, TrangSinhVien):
        TrangSinhVien.setObjectName("TrangSinhVien")
        TrangSinhVien.resize(840, 503)
        self.centralwidget = QtWidgets.QWidget(parent=TrangSinhVien)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(70, 100, 711, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 50, 201, 31))
        self.label.setObjectName("label")
        TrangSinhVien.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=TrangSinhVien)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 21))
        self.menubar.setObjectName("menubar")
        TrangSinhVien.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=TrangSinhVien)
        self.statusbar.setObjectName("statusbar")
        TrangSinhVien.setStatusBar(self.statusbar)

        self.retranslateUi(TrangSinhVien)
        QtCore.QMetaObject.connectSlotsByName(TrangSinhVien)
        self.load_data()

    def retranslateUi(self, TrangSinhVien):
        _translate = QtCore.QCoreApplication.translate
        TrangSinhVien.setWindowTitle(_translate("TrangSinhVien", "TrangSinhVien"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TrangSinhVien", "Mã Sinh Viên"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TrangSinhVien", "Tên Sinh Viên"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TrangSinhVien", "Tên Môn Học"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TrangSinhVien", "Điểm lần 1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TrangSinhVien", "Điểm lần 2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TrangSinhVien", "Điểm TB"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TrangSinhVien", "Xếp Loại"))
        self.label.setText(_translate("TrangSinhVien", "TextLabel"))

    def load_data(self):
        conn = sqlite3.connect('../ui/ql_DiemHeDH.db')
        cursor = conn.cursor()
        cursor.execute("""
            SELECT ql_HoSoSV.MaSV, ql_HoSoSV.TenSV, ql_MonHoc.TenMH, ql_Diem.DiemLan1, ql_Diem.DiemLan2
            FROM ql_HoSoSV
            JOIN ql_Diem ON ql_HoSoSV.MaSV = ql_Diem.MaSV
            JOIN ql_MonHoc ON ql_Diem.MonHoc = ql_MonHoc.MaMH
        """)
        data = cursor.fetchall()

        self.tableWidget.setRowCount(len(data))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setHorizontalHeaderLabels(['MaSV', 'TenSV', 'TenMH', 'DiemLan1', 'DiemLan2'])

        for i, row in enumerate(data):
            for j, value in enumerate(row):
                self.tableWidget.setItem(i, j, QTableWidgetItem(str(value)))
        conn.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    TrangSinhVien = QtWidgets.QMainWindow()
    ui = Ui_TrangSinhVien()
    ui.setupUi(TrangSinhVien)
    TrangSinhVien.show()
    sys.exit(app.exec())
